### ISSUE TITLE
Index both Hebrew & Genizah

### ISSUE THREAD

**Issue by ahankinson** [bodleian/hebrew-mss#1]
Both TEI collections should be indexed in the Hebrew catalogue.

**Comment by andrew-morrison** [comment]
Not a problem technically, for building indexes and generating HTML pages, but might cause issues for maintaining unique IDs and authority files across both sets of TEI files. I'll have a think if there is any configuration that make that easier.

**Comment by ahankinson** [comment]
good point.

**Comment by andrew-morrison** [comment]
Also, Genizah is mostly fragments. However, they're not marked up as `msFrag` elements, but as hierarchical arrays of `msItem` elements. So, compared to Hebrew, what should be regarded as a work?

The top-level maybe, but that's often a container, either with no title at all, or one that appears to be more of a classification label, like "Liturgical" or "Letter".

I'll try building a works index that merges Hebrew works and the bottom layer of Genizah fragments. That might be losing something, but it will be something to show Cesar. An alternative could be a "Works" button and a separate "Fragments" button (i.e. you can free-text search across both collections, but they effectively have their own browse interface.)

**Comment by andrew-morrison** [comment]
Here are some [examples of Genizah msItem hierarchy](https://github.com/bodleian/hebrew-mss/files/1652692/genizah_msitems_to_works_examples.pdf).

**Comment by andrew-morrison** [comment]
Cesar seems mostly happy with how I chose to extract works out of the hierarchy of msItems, and I am going to show him how to control it through authority files later this week. So closing this issue.
