### ISSUE TITLE
Style changes for Hebrew and Genizah launch

### ISSUE THREAD

**Issue by andrew-morrison** [bodleian/hebrew-mss#4]
I think both Hebrew and Genizah need, for the sake of legibility, the same spacing and horizontal line between each msItem as Medieval. Specifically, they're lacking this CSS on QA:

```
.individual-item .msItem {
  border-bottom: 1px solid #eaeaea;
  margin-bottom: 1rem;
  padding-bottom: 1rem;
}
```
Unless Cesar has specifically said he doesn't want that, I think it is worth trying. It might add more space than is ideal for manuscripts that are one item per part, but anything with multiple items per part, or not organized into parts at all (like [this example](http://hebrew-qa.bodleian.ox.ac.uk/catalog/manuscript_23)) need something to break up the contents visually.

Also, @IgnatG, I didn't realize you weren't a member of these repositories, so you may not have received notification when I created bodleian/genizah-mss#1 last week.

**Comment by IgnatG** [comment]
I think this style was missing because at it was added to Medieval at a later stage - after I've cloned the repo.
I'll be at BDLSS tomorrow so I'll add it then.

**Comment by IgnatG** [comment]
//implemented
