### ISSUE TITLE
Lines between "List of works" nav darker on Hebrew site than Genizah

### ISSUE THREAD

**Issue by andrew-morrison** [bodleian/hebrew-mss#6]
The difference seems to be on Hebrew this CSS...
```
.individual-item .aside-navigation tr {
    border-bottom: 1px solid grey;
}
```
...needs to be replaced with this on Genizah...
```
.individual-item .aside-navigation tr {
    border-bottom: 1px solid #eaeaea;
}
```
Obviously this is a very minor display issue, but if you're fixing other stuff, might as well make them consistent.

**Comment by IgnatG** [comment]
done

**Comment by andrew-morrison** [comment]
Still darker on Hebrew than Genizah.
